-include Makefile.common
-include world/Makefile

bin/world : $(OBJS) 
	g++ -o $@ -I. $(OBJS) -lprotobuf -llua 
	g++ -o $@ -I. -I/usr/include/lua5.1 $(OBJS) -lprotobuf -llua #-L3rd/lua-5.1.4/src
clean:
	rm -f util/*.o util/concurrent/*.o net/*.o proto/*.o world/*.o bin/world
