-include Makefile.common
-include gate/Makefile

#bin/gate : $(OBJS) #$(INCS)
bin/gate : $(OBJS) 
	g++ -o $@ -I. $(OBJS) -lprotobuf -llua 

clean:
	rm -f util/*.o util/concurrent/*.o net/*.o proto/*.o gate/*.o bin/gate
