OBJS :=
INCS :=

-include net/Makefile
-include pattern/Makefile
-include script/Makefile
-include util/Makefile
-include util/concurrent/Makefile
#cd proto &&  make -f Makefile.gen
-include schedule/Makefile
-include proto/Makefile
